### ISSUE TITLE
Bug: Handle {"type": "text", "text": null},

### ISSUE THREAD

**Issue by putrafajarh** [gbicou/prosemirror-render#147]
Hi @gbicou, first thanks for this plugin.
i don't know if text can be null or not (is it expected from TipTap).
But, if this value is expected, I think we need way to convert this to empty string when render

```
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "mentionPopover",
          "attrs": {
            "id": "01927c68-8847-7243-858d-ccb4b8c3b7c3",
            "label": "thaddeus.bradtke"
          }
        },
        {
          "type": "text",
          "text": null
        },
        {
          "type": "mentionPopover",
          "attrs": {
            "id": "01927c68-881d-70db-8950-fcb657e16f7f",
            "label": "vbogisich"
          }
        },
        {
          "type": "text",
          "text": null
        }
      ]
    }
  ]
}
```

<img width="274" alt="Screenshot 2024-10-12 at 06 23 07" src="https://github.com/user-attachments/assets/d2ef12b4-8a63-4ccf-bc00-0b29605fee1c">

**Comment by putrafajarh** [comment]
This is not expected behaviour from TipTap.
Laravel TrimStrings :)

**Comment by gbicou** [comment]
Thanks ! Even if it's not expected, nullish texts should render to empty strings.
